package hbi.core.empws.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "demo_position")
public class Position extends BaseDTO {

     public static final String FIELD_POSITION_ID = "positionId";
     public static final String FIELD_POSITION_CODE = "positionCode";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";


     @Id
     @GeneratedValue
     private Long positionId;

     @Length(max = 50)
     private String positionCode; //岗位编码

     @Length(max = 100)
     private String name; //岗位名称

     @Length(max = 255)
     private String description; //岗位描述

     @NotEmpty
     @Length(max = 1)
     private String enabledFlag; //启用状态


     public void setPositionId(Long positionId){
         this.positionId = positionId;
     }

     public Long getPositionId(){
         return positionId;
     }

     public void setPositionCode(String positionCode){
         this.positionCode = positionCode;
     }

     public String getPositionCode(){
         return positionCode;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     }
