package hbi.core.mydemo.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.criteria.JoinType;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;




import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "demo_emp")
public class Emp extends BaseDTO {

    public static final String FIELD_EMPLOYEE_ID = "employeeId";
    public static final String FIELD_EMPLOYEE_CODE = "employeeCode";
    public static final String FIELD_NAME = "name";
    public static final String FIELD_BORN_DATE = "bornDate";
    public static final String FIELD_EMAIL = "email";
    public static final String FIELD_MOBIL = "mobil";
    public static final String FIELD_JOIN_DATE = "joinDate";
    public static final String FIELD_GENDER = "gender";
    public static final String FIELD_STATUS = "status";
    public static final String FIELD_POSITION_ID = "positionId";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";


    @Id
    @GeneratedValue
    private Long employeeId;

    @NotEmpty
    @Length(max = 30)
    private String employeeCode; //员工编码

    @NotEmpty
    @Length(max = 50)
    private String name; //员工姓名

    private Date bornDate; //出生日期

    @Length(max = 50)
    private String email; //电子邮件

    @Length(max = 50)
    private String mobil; //移动电话

    private Date joinDate; //入职日期

    @Length(max = 1)
    private String gender; //性别

    @NotEmpty
    @Length(max = 50)
    private String status; //状态

/*    @Where
    @JoinTable(
            name = "demo_position",
            target = Position.class,
            joinMultiLanguageTable = false,//设置是否关联多语言表
            type = JoinType.LEFT,
            on = {@JoinOn(
                    joinField = "positionId"
            )}
    )*/
    private Long positionId; //职位ID

    @NotEmpty
    @Length(max = 1)
    private String enabledFlag; //启用状态

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setBornDate(Date bornDate) {
        this.bornDate = bornDate;
    }

    public Date getBornDate() {
        return bornDate;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setMobil(String mobil) {
        this.mobil = mobil;
    }

    public String getMobil() {
        return mobil;
    }

    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    public Date getJoinDate() {
        return joinDate;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getGender() {
        return gender;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    public Long getPositionId() {
        return positionId;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

}
