package com.hand.hap.master_distributed_execution.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "hmdm_distribute_situation")
public class DistributeSituation extends BaseDTO {

     public static final String FIELD_HEADER_ID = "headerId";
     public static final String FIELD_ITEM_CODE = "itemCode";
     public static final String FIELD_ITEM_NAME = "itemName";
     public static final String FIELD_ORANIZATION_CODE = "oranizationCode";
     public static final String FIELD_BATCH_NUM = "batchNum";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_DISTRIBUTION_DATE = "distributionDate";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long headerId; //表ID，主键，供其他表做外键

     @Length(max = 240)
     private String itemCode;

     @Length(max = 240)
     private String itemName;

     @Length(max = 240)
     private String oranizationCode;

     @Length(max = 240)
     private String batchNum;

     @Length(max = 240)
     private String status;

     private Date distributionDate;

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setHeaderId(Long headerId){
         this.headerId = headerId;
     }

     public Long getHeaderId(){
         return headerId;
     }

     public void setItemCode(String itemCode){
         this.itemCode = itemCode;
     }

     public String getItemCode(){
         return itemCode;
     }

     public void setItemName(String itemName){
         this.itemName = itemName;
     }

     public String getItemName(){
         return itemName;
     }

     public void setOranizationCode(String oranizationCode){
         this.oranizationCode = oranizationCode;
     }

     public String getOranizationCode(){
         return oranizationCode;
     }

     public void setBatchNum(String batchNum){
         this.batchNum = batchNum;
     }

     public String getBatchNum(){
         return batchNum;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setDistributionDate(Date distributionDate){
         this.distributionDate = distributionDate;
     }

     public Date getDistributionDate(){
         return distributionDate;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
