package com.hand.hap.master_distributed_execution.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.system.dto.BaseDTO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "distribute")
public class XmlDistributeSituationList {

    @XmlElement(name = "distributeSituationList")
    private List<XmlDistributeSituation> distributeSituationList;

    public List<XmlDistributeSituation> getDistributeSituationList() {
        return distributeSituationList;
    }

    public void setDistributeSituationList(List<XmlDistributeSituation> distributeSituationList) {
        this.distributeSituationList = distributeSituationList;
    }
}
