package com.hand.hap.master_distributed_execution.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "hmdm_md_type")
public class MdType extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_MD_TYPE_CODE = "mdTypeCode";
     public static final String FIELD_MD_TYPE_NAME = "mdTypeName";
     public static final String FIELD_PARENT_ID = "parentId";
     public static final String FIELD_IS_ALIVE = "isAlive";
     public static final String FIELD_IS_ENABLED = "isEnabled";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long id;

     @Length(max = 240)
     private String mdTypeCode;

     @Length(max = 240)
     private String mdTypeName;

     private Long parentId;

     @Length(max = 240)
     private String isAlive;

     @Length(max = 240)
     private String isEnabled;

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setMdTypeCode(String mdTypeCode){
         this.mdTypeCode = mdTypeCode;
     }

     public String getMdTypeCode(){
         return mdTypeCode;
     }

     public void setMdTypeName(String mdTypeName){
         this.mdTypeName = mdTypeName;
     }

     public String getMdTypeName(){
         return mdTypeName;
     }

     public void setParentId(Long parentId){
         this.parentId = parentId;
     }

     public Long getParentId(){
         return parentId;
     }

     public void setIsAlive(String isAlive){
         this.isAlive = isAlive;
     }

     public String getIsAlive(){
         return isAlive;
     }

     public void setIsEnabled(String isEnabled){
         this.isEnabled = isEnabled;
     }

     public String getIsEnabled(){
         return isEnabled;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
