package com.hand.hap.demo.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import com.hand.hap.core.annotation.Children;
import javax.persistence.Transient;
import java.util.List;
@ExtensionAttribute(disable=true)
@Table(name = "cux_om_headers_all")
public class OmHeaders extends BaseDTO {

     public static final String FIELD_OM_HEADER_ID = "omHeaderId";
     public static final String FIELD_ORDER_NUMBER = "orderNumber";


     @Id
     @GeneratedValue
     private Long omHeaderId;

     @Length(max = 30)
     private String orderNumber; //订单号


     public void setOmHeaderId(Long omHeaderId){
         this.omHeaderId = omHeaderId;
     }

     public Long getOmHeaderId(){
         return omHeaderId;
     }

     public void setOrderNumber(String orderNumber){
         this.orderNumber = orderNumber;
     }

     public String getOrderNumber(){
         return orderNumber;
     }

     @Children
     @Transient
     private List<OmLines> lines;
     public void setLines(List<OmLines> lines){
         this.lines = lines;
     }

     public List<OmLines> getLines(){
         return lines;
     }

     }

