package com.hand.hap.omdemo.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "cux_om_lines_all")
public class OmLinesAll extends BaseDTO {

     public static final String FIELD_OM_LINE_ID = "omLineId";
     public static final String FIELD_OM_HEADER_ID = "omHeaderId";
     public static final String FIELD_INVENTORY_ITEM_ID = "inventoryItemId";
     public static final String FIELD_ORDER_QUANTITY = "orderQuantity";


     @Id
     @GeneratedValue
     private Long omLineId;

     private Long omHeaderId;

     @Length(max = 30)
     private String inventoryItemId; //物料ID

     @Length(max = 30)
     private String orderQuantity; //订单数量


     public void setOmLineId(Long omLineId){
         this.omLineId = omLineId;
     }

     public Long getOmLineId(){
         return omLineId;
     }

     public void setOmHeaderId(Long omHeaderId){
         this.omHeaderId = omHeaderId;
     }

     public Long getOmHeaderId(){
         return omHeaderId;
     }

     public void setInventoryItemId(String inventoryItemId){
         this.inventoryItemId = inventoryItemId;
     }

     public String getInventoryItemId(){
         return inventoryItemId;
     }

     public void setOrderQuantity(String orderQuantity){
         this.orderQuantity = orderQuantity;
     }

     public String getOrderQuantity(){
         return orderQuantity;
     }

     }

