package com.hand.hap.audit_fruit.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "fruit_a")
public class FruitAudit extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_PRICE = "price";
     public static final String FIELD_PRODUCING_AREA = "producingArea";
     public static final String FIELD_REGION_ID = "regionId";
     public static final String FIELD_ACTIVE_DATE = "activeDate";
     public static final String FIELD_COLOR = "color";
     public static final String FIELD_AUDIT_ID = "auditId";
     public static final String FIELD_AUDIT_TRANSACTION_TYPE = "auditTransactionType";
     public static final String FIELD_AUDIT_TIMESTAMP = "auditTimestamp";
     public static final String FIELD_AUDIT_SESSION_ID = "auditSessionId";
     public static final String FIELD_AUDIT_TAG = "auditTag";
     public static final String FIELD_LANG = "lang";


     private Long id;

     @Length(max = 100)
     private String name;

     private Long price;

     @Length(max = 100)
     private String producingArea;

     private Long regionId;

     private Date activeDate;

     @Length(max = 10)
     private String color;

     @Id
     @GeneratedValue
     private String auditId;

     @Length(max = 10)
     private String auditTransactionType; //审计操作(INSERT,UPDATE,DELETE)

     private Date auditTimestamp; //审计时间

     @Length(max = 64)
     private String auditSessionId; //审计 SESSION ID

     private Long auditTag; //标记是否为最新快照

     @Length(max = 20)
     private String lang; //操作时系统语言


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setPrice(Long price){
         this.price = price;
     }

     public Long getPrice(){
         return price;
     }

     public void setProducingArea(String producingArea){
         this.producingArea = producingArea;
     }

     public String getProducingArea(){
         return producingArea;
     }

     public void setRegionId(Long regionId){
         this.regionId = regionId;
     }

     public Long getRegionId(){
         return regionId;
     }

     public void setActiveDate(Date activeDate){
         this.activeDate = activeDate;
     }

     public Date getActiveDate(){
         return activeDate;
     }

     public void setColor(String color){
         this.color = color;
     }

     public String getColor(){
         return color;
     }

     public void setAuditId(String auditId){
         this.auditId = auditId;
     }

     public String getAuditId(){
         return auditId;
     }

     public void setAuditTransactionType(String auditTransactionType){
         this.auditTransactionType = auditTransactionType;
     }

     public String getAuditTransactionType(){
         return auditTransactionType;
     }

     public void setAuditTimestamp(Date auditTimestamp){
         this.auditTimestamp = auditTimestamp;
     }

     public Date getAuditTimestamp(){
         return auditTimestamp;
     }

     public void setAuditSessionId(String auditSessionId){
         this.auditSessionId = auditSessionId;
     }

     public String getAuditSessionId(){
         return auditSessionId;
     }

     public void setAuditTag(Long auditTag){
         this.auditTag = auditTag;
     }

     public Long getAuditTag(){
         return auditTag;
     }

     public void setLang(String lang){
         this.lang = lang;
     }

     public String getLang(){
         return lang;
     }

     }
