package com.hand.hap.podemo.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import com.hand.hap.core.annotation.Children;
import javax.persistence.Transient;
import java.util.List;
@ExtensionAttribute(disable=true)
@Table(name = "cux_po_headers_all")
public class PoHeadersAll extends BaseDTO {

     public static final String FIELD_PO_HEADER_ID = "poHeaderId";
     public static final String FIELD_SEGMENT1 = "segment1";
     public static final String FIELD_VENDOR_ID = "vendorId";


     @Id
     @GeneratedValue
     private Long poHeaderId;

     @Length(max = 30)
     private String segment1; //采购单号

     private Long vendorId; //供应商ID


     public void setPoHeaderId(Long poHeaderId){
         this.poHeaderId = poHeaderId;
     }

     public Long getPoHeaderId(){
         return poHeaderId;
     }

     public void setSegment1(String segment1){
         this.segment1 = segment1;
     }

     public String getSegment1(){
         return segment1;
     }

     public void setVendorId(Long vendorId){
         this.vendorId = vendorId;
     }

     public Long getVendorId(){
         return vendorId;
     }

     @Children
     @Transient
     private List<PoLinesAll> lines;
     public void setLines(List<PoLinesAll> lines){
         this.lines = lines;
     }

     public List<PoLinesAll> getLines(){
         return lines;
     }

     }

